### PR TITLE
status-person relationship

### PR DESCRIPTION
**Pull request by onakutin**
This is my half-day-work

### CODE REVIEW

**Comment by pe3k-j** [comment]
You are missing return type for the function

**Comment by pe3k-j** [comment]
line 12 `public function people()` should be like this: `public function people() : hasMany`

**Comment by pe3k-j** [comment]
https://laravel.com/docs/10.x/eloquent-relationships

**Comment by onakutin** [comment]
Thanks. It's there now

**Comment by pe3k-j** [comment]
ok

**Pull request merged**
